export const icons = {
  archive: require('./icons/archive.png'),
  avatar: require('./icons/avatar.png'),
  backArrowLeft: require('./icons/back_arrow_left.png'),
  backArrowRight: require('./icons/back_arrow_right.png'),
  bin: require('./icons/bin.png'),
  bullet: require('./icons/bullet.png'),
  dotSeparator: require('./icons/dot_separator.png'),
  calendar: require('./icons/calendar.png'),
  check: require('./icons/check.png'),
  error: require('./icons/error.png'),
  clock: require('./icons/clock.png'),
  close: require('./icons/close.png'),
  info: require('./icons/info.png'),
  label: require('./icons/label.png'),
  marker: require('./icons/marker.svg'),
  plus: require('./icons/plus.png'),
  searchLight: require('./icons/search_light.png'),
  searchTinted: require('./icons/search_tinted.png'),
  tick: require('./icons/tick.png'),
  users: require('./icons/users.png'),
}
